# Generated by Django 5.2.1 on 2025-06-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_venue_latitude_venue_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
