# Generated by Django 5.2.1 on 2025-05-17 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='tickets.receipt'),
        ),
    ]
