# Generated by Django 5.2.1 on 2025-05-25 11:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_name',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='img_name'),
        ),
    ]
