# Generated by Django 5.2.1 on 2025-06-13 03:08

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_event_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendee_count',
            field=models.IntegerField(default=0, error_messages={'null': 'Số lượng người tham gia không được để trống'}),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(error_messages={'null': 'Danh mục không được để trống'}, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='tickets.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ended_date',
            field=models.DateTimeField(error_messages={'null': 'Thời gian kết thúc không được để trống'}),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(error_messages={'required': 'Hình ảnh đại diện sự kiện không được để trống'}, max_length=255, verbose_name='img_event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(error_messages={'blank': 'Tên sự kiện không được để trống'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='started_date',
            field=models.DateTimeField(error_messages={'null': 'Thời gian bắt đầu không được để trống'}),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(error_messages={'null': 'Địa điểm tổ chức không được để trống'}, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='tickets.venue'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='ended_date',
            field=models.DateTimeField(error_messages={'null': 'Thời gian kết thúc không được để trống'}),
        ),
        migrations.AlterField(
            model_name='performance',
            name='event',
            field=models.ForeignKey(error_messages={'null': 'Sự kiện gắn không được để trống'}, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='tickets.event'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='name',
            field=models.CharField(error_messages={'blank': 'Tên chương trình không được để trống'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='performance',
            name='started_date',
            field=models.DateTimeField(error_messages={'null': 'Thời gian bắt đầu không được để trống'}),
        ),
        migrations.AlterField(
            model_name='ticket_type',
            name='name',
            field=models.CharField(error_messages={'blank': 'Tên loại vé không được để trống'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket_type',
            name='price',
            field=models.DecimalField(decimal_places=2, error_messages={'null': 'Giá vé không được để trống'}, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket_type',
            name='quantity',
            field=models.IntegerField(default=0, error_messages={'null': 'Số lượng vé khoong được để trống'}),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(error_messages={'blank': 'Địa chỉ không được để trống'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(default=0, error_messages={'null': 'Sức chứa không được để trống'}),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(error_messages={'blank': 'Tên địa điểm không được để trống'}, max_length=100),
        ),
    ]
