# Generated by Django 5.2.1 on 2025-06-13 03:15

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_event_attendee_count_alter_event_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendee_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='tickets.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ended_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='img_event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='started_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='tickets.venue'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='ended_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='tickets.event'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='performance',
            name='started_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket_type',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket_type',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket_type',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
